// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteApp.Domain.Models;

namespace NoteApp.Migrations
{
    [DbContext(typeof(NoteAppContext))]
    partial class NoteAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NoteApp.Domain.Models.Note", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Complete")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("NoteListId")
                        .HasColumnType("bigint");

                    b.Property<long?>("NoteListId1")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NoteListId");

                    b.HasIndex("NoteListId1");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("NoteApp.Domain.Models.NoteBook", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NoteBooks");
                });

            modelBuilder.Entity("NoteApp.Domain.Models.NoteList", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("NoteBookId")
                        .HasColumnType("bigint");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NoteBookId");

                    b.ToTable("NoteLists");
                });

            modelBuilder.Entity("NoteApp.Domain.Models.Note", b =>
                {
                    b.HasOne("NoteApp.Domain.Models.NoteList", null)
                        .WithMany("Notes")
                        .HasForeignKey("NoteListId");

                    b.HasOne("NoteApp.Domain.Models.NoteBook", "NoteList")
                        .WithMany()
                        .HasForeignKey("NoteListId1");

                    b.Navigation("NoteList");
                });

            modelBuilder.Entity("NoteApp.Domain.Models.NoteList", b =>
                {
                    b.HasOne("NoteApp.Domain.Models.NoteBook", "NoteBook")
                        .WithMany("NoteLists")
                        .HasForeignKey("NoteBookId");

                    b.Navigation("NoteBook");
                });

            modelBuilder.Entity("NoteApp.Domain.Models.NoteBook", b =>
                {
                    b.Navigation("NoteLists");
                });

            modelBuilder.Entity("NoteApp.Domain.Models.NoteList", b =>
                {
                    b.Navigation("Notes");
                });
#pragma warning restore 612, 618
        }
    }
}
